# Generated by Django 4.0.3 on 2022-03-29 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type', to='tutorial.contenttype'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='images',
            field=models.ManyToManyField(related_name='images', to='tutorial.image'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='keywords',
            field=models.ManyToManyField(related_name='keywords', to='tutorial.keyword'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='videos',
            field=models.ManyToManyField(related_name='videos', to='tutorial.video'),
        ),
    ]
